=== Helmanzs/PRI/projekt_1/fakulta.dtd
<!ELEMENT fakulta (katedra+)>
<!ATTLIST fakulta dekan CDATA #REQUIRED>

<!ELEMENT katedra (vedouci, zamestnanci, predmety)>
<!ATTLIST katedra
    zkratka_katedry CDATA #REQUIRED
    webové_stránky CDATA "https://www.ujep.cz/cs/">

<!ELEMENT vedouci (jmeno, (telefon|email)+)>

<!ELEMENT jmeno (#PCDATA)>

<!ELEMENT telefon (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT zamestnanci (zamestnanec+)>

<!ELEMENT zamestnanec (jmeno, (telefon|email)+, pozice?)>

<!ELEMENT pozice (lektor|asistent|odborny_asistent|docent|profesor)?>
<!ELEMENT lektor EMPTY>
<!ELEMENT asistent EMPTY>
<!ELEMENT odborny_asistent EMPTY>
<!ELEMENT docent EMPTY>
<!ELEMENT profesor EMPTY>

<!ELEMENT predmety (predmet*)>

<!ELEMENT predmet (nazev, popis?)>
<!ATTLIST predmet
    zkratka CDATA #REQUIRED
    typ (prednaska|seminar|cviceni|kombinovane) "kombinovane">

<!ELEMENT nazev (#PCDATA)>
<!ELEMENT popis (#PCDATA)>

=== Helmanzs/PRI/projekt_1/prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fakulta SYSTEM "fakulta.dtd">
<fakulta dekan="Prof. Ing. Jan Dvořák, DrSc.">

    <katedra zkratka_katedry="KINF" webové_stránky="https://www.ujep.cz/cs/katedra-informatiky">
        <vedouci>
            <jmeno>doc. Ing. Petr Novotný, Ph.D.</jmeno>
            <telefon>+420 123 456 789</telefon>
            <email>petr.novotny@ujep.cz</email>
        </vedouci>
        <zamestnanci>
            <zamestnanec>
                <jmeno>John Doe</jmeno>
                <telefon>+420 987 654 321</telefon>
                <email>john.doe@ujep.cz</email>
                <pozice>
                    <profesor />
                </pozice>
            </zamestnanec>
        </zamestnanci>
        <predmety>
            <predmet zkratka="MAT101" typ="prednaska">
                <nazev>Matematika I</nazev>
                <popis>Kurz základní matematiky pro prváky.</popis>
            </predmet>
        </predmety>
    </katedra>
</fakulta>
